### ISSUE TITLE
Merging duplicates does not work

### ISSUE THREAD

**Issue by bmhj2** [flathub/org.zotero.Zotero#102]
It's possible this is a result of me not having configured the sandbox permissions properly, but merging duplicates in this release does not result in the duplicate entries disappearing. You select the one whose metadata you want to keep, then press merge. The metadata is shared between both items, but the duplicate item has to be deleted manually.

Am I missing something here?

**Comment by sebastian-de** [comment]
Since this issue is very old I'll close it. Please reopen if this persists with a current version.
