### ISSUE TITLE
Update screenshots to use a Linux one

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/org.zotero.Zotero#12]
The current screenshot is from the macOS version :/

**Comment by bilelmoussaoui** [comment]
The appdata file is not from upstream so you shouldn't be showing something the user won't be getting. Please reopen this instead of closing an issue that's not fixed yet.

**Comment by amtlib-dot-dll** [comment]
Well, there is no upstream `appdata` file actually. Since you are the one who opened this issue you should be able to reopen it?

**Comment by felipehw** [comment]
Thanks @ykgmfq !
