### ISSUE TITLE
Support for Zotero Beta

### ISSUE THREAD

**Issue by czhang03** [flathub/org.zotero.Zotero#124]
Zotero has a repo for beta build: https://www.zotero.org/support/beta_builds, and flathub supports beta channel: https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

Is it possible to package beta build of Zotero on flathub? 

The reason I want beta build is that Zotero 7 beta finally supports wayland windowing session. Thank you so much!

**Comment by sebastian-de** [comment]
Zotero is now available on Flathub beta:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.zotero.Zotero
```
