### ISSUE TITLE
No comfortable way to access attached files

### ISSUE THREAD

**Issue by ceresek** [flathub/org.zotero.Zotero#13]
An attempt to view a PDF file stored in the Zotero database (right click on entry, select "View PDF") on standard Fedora installation fails, with the error message below. Same for other means to access the stored PDF files (open folder etc.). Without this, the user must manually search for PDF files in the Zotero data directory, perhaps the required permissions to do xdg-open should be added to permit this ?

** (zotero:6): WARNING **: Cannot launch default application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
Possibly unhandled rejection:

/usr/bin/xdg-open returned exit status 4

Error: /usr/bin/xdg-open returned exit status 4
    Zotero.Utilities.Internal.exec</<.observe@chrome://zotero/content/xpcom/utilities_internal.js:516:22

**Comment by amtlib-dot-dll** [comment]
Well I am encountering this problem too. What is your version of `flatpak`?

**Comment by ceresek** [comment]
Sorry, my bad. Was caused by missing installation of xdg-desktop-portal and xdg-desktop-portal-gtk, which are not dependencies of Flatpak on Fedora. After installation, things work just fine.
