### ISSUE TITLE
Zotero does not recognise default PDF viewer

### ISSUE THREAD

**Issue by Ethunxxx** [flathub/org.zotero.Zotero#15]
In the preferences I set that Zotero should use the system's default PDF viewer to open PDFs. However, every time I open a PDF, Zotero asks which viewer to use. 
Is there a way to fix this?

**Comment by felipehw** [comment]
Same here!

**Comment by rvlobato** [comment]
Always asking for pdf viewer.

**Comment by pimou** [comment]
Same here ! very annoying....

**Comment by pimou** [comment]
And all is ok with stock Zotero... Everything is fine using the tarball.

**Comment by qwertyuser1983** [comment]
Waiting for solution for this problem. :)

**Comment by PorcelainMouse** [comment]
In addition, or perhaps not, Zotero cannot even find the default PDF viewer in the filesystem, so you cannot select it using the option alternative to the "system default."

You can select /usr/bin/xdg-open, but even this does not work.  Regardless of the setting for the viewer in Zotero, Zotero always asks which PDF viewer to use.

Does anyone even know why this happens?  Is it some type of sandboxing that appends to flatpak applications?  It must be, right?

**Comment by juanlufont** [comment]
> Waiting for solution for this problem. :)
> 
> In my case, even the prompt did not show. This the terminal output when loading the pdf. :(
> 
> > ** (zotero:6): WARNING **: 13:58:46.797: Cannot launch default application: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.OpenURI' on object at path /org/freedesktop/portal/desktop
> > Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.OpenURI' on object at path /org/freedesktop/portal/desktop
> > Possibly unhandled rejection:
> > /usr/bin/xdg-open returned exit status 4
> > Error: /usr/bin/xdg-open returned exit status 4
> > Zotero.Utilities.Internal.exec</<.observe@chrome://zotero/content/xpcom/utilities_internal.js:516:22

I was getting the same error on Debian Testing (Buster) when using the flatpak package for Zotero.

In my case I was missing some of the `xdg-destop-portal` binaries required to integrate the flatpack app with the rest of my system. I managed to fix the problem just installing the following packages and restarting my graphical session:
* `xdg-desktop-portal-gtk`
* `flatpack-xdg-utils`

**Comment by allefeld** [comment]
I have the same problem as @qwertyuser1983, but @juanlufont's solution does not fix it.

@juanlufont, you did install the Debian packages, right? Not some flatpak packages?

**Comment by allefeld** [comment]
I found another workaround: Start Zotero with

`flatpak run --filesystem=host org.zotero.Zotero`

This allows "Open pdfs using" / "Custom..." to browse the entire file system, so one can select the appropriate binary.

**Comment by N1X3L** [comment]
> I found another workaround: Start Zotero with
> 
> `flatpak run --filesystem=host org.zotero.Zotero`
> 
> This allows "Open pdfs using" / "Custom..." to browse the entire file system, so one can select the appropriate binary.

This workaround does not seem to be viable in Solus, but I appreciate you posting it.

**Comment by mihaic** [comment]
This behavior comes from `xdg-desktop-portal`, which is responsible for asking how to open the PDF. Starting in version 1.5.3, it will remember your choice after asking 3 times. See the corresponding issue and PR:
https://github.com/flatpak/xdg-desktop-portal/issues/302
https://github.com/flatpak/xdg-desktop-portal/pull/406

I think this issue should be closed.

**Comment by felipehw** [comment]
Maybe, we could wait this fix arrive in any major distribution to see if it really works in a real environment with Zotero?

**Comment by rvlobato** [comment]
I can confirm that it is working in Arch Linux
