### ISSUE TITLE
Error: no DISPLAY environment variable specified

### ISSUE THREAD

**Issue by xplosionmind** [flathub/org.zotero.Zotero#150]
When running `flatpak run org.zotero.Zotero`, I get `Error: no DISPLAY environment variable specified`. I tried running `DISPLAY=Wayland flatpak run org.zotero.Zotero`, but I get the same error.

How could I debug this? Could you help me?

Thanks a lot!

**Comment by sebastian-de** [comment]
Can you try if the beta works for you? See https://github.com/flathub/org.zotero.Zotero/issues/124#issuecomment-1799306027

To be honest I don't test the stable version anymore - the bundled Firefox version is really old and doesn't have Wayland support. It should work with XWayland though.

**Comment by xplosionmind** [comment]
With the beta it works great.
Thanks @sebastian-de!
