### ISSUE TITLE
Use Persistent Path For `Zotero` And `.zotero` Folder 

### ISSUE THREAD

**Issue by czhang03** [flathub/org.zotero.Zotero#154]
Use the Persistent path permission for both `Zotero` and `.zotero` folder:

This change will enable  
- better sandboxing: app with user home path permission will not be able to see zotero content
- Less pollution in the home folder

We might also need to remove home folder permission as well, for this change to work.

**Comment by sebastian-de** [comment]
I'm not really happy with the current filesystem permissions either, but the last attempt to restrict them didn't end well: https://github.com/flathub/org.zotero.Zotero/issues/82

**Comment by czhang03** [comment]
I think because zotero 7 uses a modern version of firefox, therefore it has portal support by default. 
I have tested exporting file, importing file, and install extensions with zero file permissions, and it all works.

I think we might be able to harden permission on zotero 7 beta.

**Comment by sebastian-de** [comment]
Testing this in the beta branch is fine I guess. Can you make a PR with your suggested changes?
