### ISSUE TITLE
Zotero 5.0.58 released

### ISSUE THREAD

**Issue by felipehw** [flathub/org.zotero.Zotero#16]
There will be updates for this flatpak?
The actual version is 5.0.56 (October 9, 2018) and there was 2 versions after that.
Maybe be a option try contact the developers of Zotero to mantain the flatpak version?

**Comment by amtlib-dot-dll** [comment]
Yeah, you're right! Actually there is a [script](https://github.com/flathub/org.zotero.Zotero/blob/master/build.sh) to generate this recipe, but the maintainer of Flathub have no plan to periodically run them. I am replying with my phone with no git client installed, and would you make a pull request for this? Thank you very much!

**Comment by felipehw** [comment]
@amtlib-dot-dll 
OK!
https://github.com/flathub/org.zotero.Zotero/pull/17

**Comment by retorquere** [comment]
There's a new version out again. It wasn't tagged in GH (it is now), but the latest Zotero version is most reliably detected by looking at https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json.

Wouldn't it be easier to have a travis job run nightly to detect and publish a new version if it's available?

**Comment by felipehw** [comment]
I'll update when I arrive home tomorrow. I never worked with Travis. And I don't have time to check ... If someone wanna do this ...

**Comment by retorquere** [comment]
I have a little Travis experience, but absolutely no time, and no flatpack experience, not even as a user. I'm making this report on behalf of a zotero user, but I install zotero from debs myself.
