### ISSUE TITLE
Zotero Flatpak create profiles in /home/user/.zotero insteand of instead of /home/user/.var/app/org.zotero.Zotero/

### ISSUE THREAD

**Issue by sith-on-mars** [flathub/org.zotero.Zotero#174]
See the title. Could we create profiles in /home/user/.var/app/org.zotero.Zotero/ like other Flatpak apps do, which won't 'pollute' home directory?

I'm using Zotero 6 on Fedora Silverblue.

**Comment by sebastian-de** [comment]
This will be easier with Zotero 7 and can be tested with the current beta builds.

Please read #154 and https://forums.zotero.org/discussion/113336/beta-testing-zotero-7-flatpak

**Comment by sebastian-de** [comment]
This is now possible with the steps mentioned in the app description.
