### ISSUE TITLE
With the new version the clipboard doesn't work anymore

### ISSUE THREAD

**Issue by TobTobXX** [flathub/org.zotero.Zotero#215]
When I do "Create bibliography for Item..." > Output method: Clipboard, the clipboard contents don't change.

Workaround:
- Output to clipboart
- Paste _inside the Zotero window_ (for example, search box).
- Copy that value again
- It is now in the clipboard

**Comment by sebastian-de** [comment]
I cannot reproduce this - on Plasma I can paste the bibliography anywhere without the workaround you describe.
This is probably due to the switch to Wayland, so you'll have to check your Wayland/desktop setup (make sure you have a desktop portal installed, for exmaple).

**Comment by TobTobXX** [comment]
I'm using GNOME, so I don't think I've forgotten to install something. Though GNOME is not the most spec-compliant compositor...
I'll try it with Plasma next week or so, since I've been meaning to switch to it anyway.

**Comment by TobTobXX** [comment]
... it now works, even in GNOME?? I did update my system in the meantime so that might've helped.

Sorry for the bother.

**Comment by TobTobXX** [comment]
btw, I could reproduce it, but it's not really a bug: When I click "OK" and immediately switch focus away from the Zotero window, the text doesn't get copied. This also happens with other applications, particularily if the put a large amount of data in the clipboard. Zotero is just unusually slow when saving to the clipboard (in Wayland?), that's why I ran across.
