### ISSUE TITLE
URIs do not open properly

### ISSUE THREAD

**Issue by Victor239** [flathub/org.zotero.Zotero#217]
Clicking a URI like `zotero://select/library/items?itemKey=JSFRJERV` from another app will open Zotero but won't open the specified item.

**Comment by jakobluettgau** [comment]
This seems to be due to missing permissions for the flatpack (i.e. "D-Bus session bus"). There is also a related discussion in the Zotero forums suggesting setting this resolves the issues: https://forums.zotero.org/discussion/116717/zotero-item-pdf-links-not-working-when-zotero-7-is-running-in-the-background 

Maybe it would be possible to set this permission by default, unless there is a good reason for the more conservative default.

**Comment by Victor239** [comment]
Thanks, that worked for me.

**Comment by sebastian-de** [comment]
Thanks for the hint!

However, I just learned that adding `--socket=session-bus` to the manifest is not allowed by default anymore:
```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest org.zotero.Zotero.yaml
 in dir /srv/buildbot/worker/build-x86_64/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest org.zotero.Zotero.yaml'
 using PTY: False
{
    "errors": [
        "finish-args-arbitrary-dbus-access"
    ],
    "info": [
        "finish-args-arbitrary-dbus-access: finish-args has socket access to full system or session bus"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

I think the correct way to do this is to find out the DBUS resource name that's responsible for URL handling and add that with `--talk-name`. I see if I can find the time for that over the weekend.

**Comment by sebastian-de** [comment]
@Victor239 @jakobluettgau can you try if opening URIs work for you, if you disable access to the session bus, but allow Zotero to talk to `org.mozilla.zotero.*`?

```
flatpak override --user --talk-name="org.mozilla.zotero.*" org.zotero.Zotero
```

I'm not entirely sure if the talk permission is enough, maybe it need to own it:

```
flatpak override --user --own-name="org.mozilla.zotero.*" org.zotero.Zotero
```

If even that doesn't work, can you run Zotero using the commend `flatpak run --log-session-bus org.zotero.Zotero`, click on a Zotero link and post the output here?

**Comment by jakobluettgau** [comment]
@sebastian-de I can confirm both settings (talk only/own only) are working even with the session bus permission disabled

**Comment by sebastian-de** [comment]
@jakobluettgau perfect, thank you! Then I'll add the talk permission to the defaults.
