### ISSUE TITLE
Enabling GPU acceleration (device=dri) significantly increases performance

### ISSUE THREAD

**Issue by chenxiex** [flathub/org.zotero.Zotero#229]
Performance is very poor on my Intel® Core™ Ultra 5 + RTX 3060 Laptop without `device=dri`, especially when viewing PDF using the integrated PDF reader. After setting `device=dri` in Flatseal, everything looks smoother. I wonder if this should be the default option.

**Comment by sebastian-de** [comment]
Yes sure, that can be added to the defaults.
