### ISSUE TITLE
Latest update is corrupt?

### ISSUE THREAD

**Issue by ahmed-alhindawi** [flathub/org.zotero.Zotero#235]
Hello,

I'm trying to update to the latest zotero flatpak on flathub, but i'm getting this error:
```
Error: While pulling app/org.zotero.Zotero/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='5e7922529dffb3b43b82d2539649cd60c71aebfcd2f18b50e9a530ffe4b2701a' actual='c0fde2f233d9fbebd001d1daa9b3b09b6581642f6e1a29221e83c009c84e6395'
```

Is the upload corrupt? Everything else updates correctly and normally

**Comment by sebastian-de** [comment]
I just reinstalled Zotero and everthing works as expected.
I don't know how the flathub CI works in detail, but I'm pretty sure that there are checks to prevent a broken build from being uploaded into the repository.

Can you simply try to install Zotero again?

**Comment by ahmed-alhindawi** [comment]
Thanks - that works. Weird....
