### ISSUE TITLE
Instant crash after latest Fedora 41 update

### ISSUE THREAD

**Issue by Dapuva76** [flathub/org.zotero.Zotero#240]
Installed the latest updates for Fedora 41 running KDE, and now Zotero instantly crashes when started up. "It looks like zotero-bin" crashed. Flatpak version Zotero 7.0.11.

Interestingly enough, another flatpak app crashes with a python-error-message after the latest Fedora update.

**Comment by Dapuva76** [comment]
I get this error msg when starting flatpak from the shell:

`/app/bin/zotero: Zeile 20:     5 Speicherzugriffsfehler  (Speicherabzug geschrieben) "$CALLDIR/zotero-bin" -app "$CALLDIR/app/application.ini" "$@"`

That translates to memore access error.

**Comment by Dapuva76** [comment]
Problem was on the Fedora side. A buggy glib implementation (iirc) that was hotfixed. Problem solved.

**Comment by remicantelas** [comment]
I'm having the same issue. How did you fix this exactly?
