### ISSUE TITLE
zotero addon for libreoffice and chrome can't work with zotero

### ISSUE THREAD

**Issue by jacknlliu** [flathub/org.zotero.Zotero#4]
The zotero addon for libreoffice can't insert items from zotero, and the webpage can't be saved to zotero using zotero addon for chrome.

**Comment by amtlib-dot-dll** [comment]
Zotero addon for Chrome works flawlessly for me. I don't use the other add-on because I use LaTeX.

**Comment by jacknlliu** [comment]
I just report that some features of this zotero package can't work. And I'm not looking for a workaround. Thanks for your attention.

**Comment by koenigjaeger** [comment]
see https://github.com/flathub/org.libreoffice.LibreOffice/issues/7?_pjax=%23js-repo-pjax-container?

**Comment by koenigjaeger** [comment]
Also is Zotero_OpenOffice_Integration.oxt included in the flatpak? So we should be able to use `xdg-open` to point libreoffice to the directory that contains the add-on.

**Comment by alexpattyn** [comment]
This issue should be closed. For libreoffice and firefox (haven't tested chrome) the zotero plugin works. 

Libreoffice go to...
Tools>Preferences>Cite>Word Processors>Install Libreoffice add-in.

For firefox and chrome just download the add-on and have zotero running.
