### ISSUE TITLE
disable updates in `prefs.js`

### ISSUE THREAD

**Issue by danmackinlay** [flathub/org.zotero.Zotero#41]
Zotero flatpak should never ask to self-update to avoid users gettting update warning (e.g.  #6 ) when in fact the updates are through the flatpak system.

[according to dan stillman](https://forums.zotero.org/discussion/comment/341356/#Comment_341356) this is as simple as setting `app.update.enabled` to `false` in the bundled `prefs.js`. I got that spurious update message again today so presumably this is still a problem.

**Comment by Maltimore** [comment]
I tried to do this, but I can't the ```prefs.js``` file you reference. Also, I did a full-text search for ```app.update.enabled``` and it only appears in the tests.
