### ISSUE TITLE
GPG signatures

### ISSUE THREAD

**Issue by zareami10** [flathub/org.zotero.Zotero#49]
When trying to update to the latest version I'm getting the following error:
`Error: While pulling app/org.zotero.Zotero/x86_64/stable from remote flathub: GPG signatures found, but none are in trusted keyring`

Might be related to [this](https://github.com/flatpak/flatpak/issues/1450)? I'm only facing it with Zotero at the time being though.

**Comment by arteymix** [comment]
It's definitely related to Flathub/Flatpak since they proceed to build and sign the user-distributed content.

**Comment by arteymix** [comment]
You should do the follow-up for this issue at https://github.com/flatpak/flatpak/issues/1450
