### ISSUE TITLE
Set permission to access tesseract executable for zotero-ocr

### ISSUE THREAD

**Issue by ashwinvis** [flathub/org.zotero.Zotero#53]
When I run zotero-ocr plugin with tesseract installed in the system, I get

> No tesseract executable found.

Is there a way to allow Zotero to execute a system executable? I read the [docs on permissions](https://docs.flatpak.org/en/latest/sandbox-permissions.html), but could not get it right.

**Comment by ashwinvis** [comment]
https://github.com/UB-Mannheim/zotero-ocr/

**Comment by TingPing** [comment]
Generally you bundle tools you need.

**Comment by arteymix** [comment]
There's a flatpak build def here for tesseract: https://github.com/egrath/tesseract-flatpak

I can include it in the building process and install it in the app image.

**Comment by arteymix** [comment]
@ashwinvis Could you try the Flatpak test build from #59 when it's ready?

**Comment by ashwinvis** [comment]
I installed both the zotero and tesseract as flatpak
```sh
flatpak install --user https://dl.flathub.org/build-repo/19411/org.zotero.Zotero.flatpakref
curl https://github.com/egrath/tesseract-flatpak/releases/download/4.0.0/tesseract-4.0.0.flatpak -LOL
flatpak install --user tesseract-4.0.0.flatpak
```
Now I need to configure zotero-ocr to use the flatpak tesseract. How does one do that?
![Screenshot_20200517_225830](https://user-images.githubusercontent.com/9155111/82159910-03864600-9892-11ea-9e35-4a7117122844.png)

**Comment by arteymix** [comment]
I'm actually building Tesseract inside Zotero flatpak in #59. You can test the build by running:

```
flatpak install --user https://dl.flathub.org/build-repo/19411/org.zotero.Zotero.flatpakref
```

**Comment by ashwinvis** [comment]
OK I specified `/app/bin/tesseract` to the plugin, and it now complains:

> No /app/share/zotero/pdftoppm executable found.

**Comment by arteymix** [comment]
It's apparently missing pdftoppm provided by Poppler. In Zotero configuration, you should point to `/app/bin/tesseract`.

**Comment by arteymix** [comment]
I think it's best to pursue discussions in #59
