### ISSUE TITLE
Can't Update Zotero Flatpak

### ISSUE THREAD

**Issue by javery86** [flathub/org.zotero.Zotero#6]
Attached, is the error I keep receiving. Which folder would I need to modify permissions so it updates?

![screenshot_20180617_212002](https://user-images.githubusercontent.com/23128240/41523136-8614538c-7274-11e8-91dd-0045551447e2.png)

**Comment by amtlib-dot-dll** [comment]
Sorry for our late update. I will push the latest version to Flathub and after updating you will not receive it anymore. Zotero will try to upgrade via it's own upgrading mechanism but it is not allowed as it is inside a package. 

https://github.com/flathub/org.zotero.Zotero/commit/5d06e6b2ea72986562dcb59a422da9634f5fbe57

@nedrichards I want to set up a special 
robot GitHub account just for periodically upgrading those recipes, is that OK? I don't want to give my token to any third-party cloud services.

**Comment by javery86** [comment]
Same problem is happening again.

**Comment by arteymix** [comment]
@javery86 There's nothing you have to do besides `flatpak update org.zotero.Zotero` and hope we've pushed the latest version on flathub. The flatpak environment is immutable per design.

**Comment by lovetheguitar** [comment]
Please update it again. :/ 
Thank you! :)
