### ISSUE TITLE
Missing x-scheme-handler directive from the desktop file (zotero:// URL schemes don't work)

### ISSUE THREAD

**Issue by ghost** [flathub/org.zotero.Zotero#64]
I think the desktop file should be patched with the `MimeType=x-scheme-handler/zotero;` directive to enable the zotero:// URL scheme. 

More info: https://forums.zotero.org/discussion/78550/getting-zotero-to-work-under-ubuntu-linux-solved

**Comment by arteymix** [comment]
No need to patch anything, you can rewrite pretty much anything with `desktop-file-install`.

**Comment by felipehw** [comment]
Fixed by @lionirdeadman and @wshanks with the code at #87 .

**Comment by arteymix** [comment]
Yay!
