### ISSUE TITLE
Second Zotero Icon in Dock when run as a Flatpak

### ISSUE THREAD

**Issue by Retrotux** [flathub/org.zotero.Zotero#71]
Known issue for some flatpak apps (e.g. GIMP). When running Zoetro, a second icon is shown in the Dock (plank). Here's a workaround, but not sure how to implement it for Zotero:

https://elementaryos.stackexchange.com/questions/18/one-of-my-apps-has-a-second-fuzzy-icon-in-plank-how-can-i-workaround-this

OS: elementaryOS 5.1.7 Hera

**Comment by felipehw** [comment]
This doesn't happen with Gnome default dock ...

But you just have to follow the hints at the link you pasted changing this value:
```
$ xprop WM_CLASS
WM_CLASS(STRING) = "Navigator", "Zotero"
```

But why Elementary can't fix this (because works with Gnome) ?

**Comment by Retrotux** [comment]
Maybe it will be fixed in the next release. Problem is: There is no Zotero-Launcher in /usr/share/applications, so the instructions don't work for elementary. Any idea how this could be fixed?

**Comment by felipehw** [comment]
Flatpak files are in different places than the traditional installation.
At my machine the desktop file is on the dir: `/var/lib/flatpak/app/org.zotero.Zotero/x86_64/stable/active/files/share/zotero/zotero.desktop`.

But I don't think messing with files of a Flatpak installation is a good practice. Maybe if you put a custom version at your home user dir (e.g.: `~/.local/share/applications/`).
