### ISSUE TITLE
library and preferences won't be saved if some directories don't exist

### ISSUE THREAD

**Issue by ntorresalberto** [flathub/org.zotero.Zotero#73]
**Linux distribution and version**: Fedora 32
**Flatpak version**: 5.0.93

## Description of the problem

After finishing installation, settings (like data sync info) and library won't be saved without further action.
I'm not sure if this is due to recent changes in flatpak permissions or what happened but Zotero needs these directories in order to store preferences/library:

- `~/Zotero`
- `~/.zotero/zotero`

## Steps to reproduce

1. [Install the flatpak ](https://flathub.org/apps/details/org.zotero.Zotero) and launch the application.
2. After syncing or doing any changes to setings/library, close it.
3. Next launch won't have any of the previous changes.

## Workaround / Temporary Fix

1. Finish installation.
2. Manually create the necessary directories by running: `mkdir -pv ~/Zotero ~/.zotero/zotero`

Again, *I'm not sure this is an issue with the flatpak* (I hope the maintainers will confirm that) but I guess this is the best place to share this workaround/document the problem for future users.

**Comment by ntorresalberto** [comment]
I posted it on the flatpak repo previously by mistake: https://github.com/flatpak/flatpak/issues/4003

**Comment by felipehw** [comment]
@ntorresalberto 

Thanks for your feedback.
Could you test #75 ?
Here is the command to install:
```
flatpak install --user https://dl.flathub.org/build-repo/32363/org.zotero.Zotero.flatpakref
```

By my tests ... the problem is solved.
Is you find no problem ... I'll commit.

Zotero doesn't follow the XDG spec. But this Flatpak isn't an official build neither I'm a Zotero developer.
So while Zotero doesn't follow the XDG spec, we must adapt ourselves ...

**Comment by ntorresalberto** [comment]
> Zotero doesn't follow the XDG spec. But this Flatpak isn't an official build neither I'm a Zotero developer.

Just for future references, there's an old [thread in the official forum regarding the XDG directory specification](https://forums.zotero.org/discussion/55557/zotero-for-linux-should-support-the-xdg-base-directory-specification).

> So while Zotero doesn't follow the XDG spec, we must adapt ourselves ...

Thanks for doing this! I really appreciate having a flatpak available.

> Could you test #75 ?

It's working for me. Will this hit the stable channel immediately after commit? (just want to know when to update).

**Comment by felipehw** [comment]
Done.
#75 will hit stable channel in 3 hours (I believe).
