### ISSUE TITLE
Failing to install extension

### ISSUE THREAD

**Issue by kemelzaidan** [flathub/org.zotero.Zotero#76]
I'm trying to install the [Better BibTex extension](https://github.com/retorquere/zotero-better-bibtex) but Zotero doesn't even show the .xpi file on the the addon manager. Trying to drag the addon inside the addon manager windows gives the following incompatible error message:

![screenshot](https://user-images.githubusercontent.com/897436/101722472-17d99c80-3a89-11eb-96bb-19e14e28b0a3.png)

Since the Zotero flatpak version is the last one available and the plugin version is only 16 days old, I believe it's not likely to be a version compatibility problem.

**Comment by felipehw** [comment]
I didn't know this extension.

I just downloaded and installed without problems (but I didn't use it).

You must put the `.xpi` file inside a directory that Zotero flatpak sandbox can access.

For example, put the `.xpi` file inside your *Downloads* directory.

If you wanna Zotero accessing others directories than the defaults ... you can use https://flathub.org/apps/details/com.github.tchx84.Flatseal.

**Comment by kemelzaidan** [comment]
It did work. In fact, the problem was accessing folders other than the sandbox restricted ones.

Thanks e boas festas!
