### ISSUE TITLE
Custom Zotero location, still creating `~/Zotero` on every launch

### ISSUE THREAD

**Issue by charlydelta** [flathub/org.zotero.Zotero#77]
I have configured the Zotero data dir to a custom location `~/.zotero_data`, and I allowed it access to it via `flatpak override`. This works all fine, however, on every launch, the folder `~/Zotero` gets created (empty) nonetheless... This is really annoying. 

I don't know whether this is an issue of Zotero or the flatpak, but it is new. Didn't had an issue like that before upgrading today.

**Comment by charlydelta** [comment]
I don't know if it is related or it helps, but in my opinion the `Zotero` folder should be in the documents directory, and the `~/.zotero` in an XDG conform directory like `~/.local/share` or whatever...

I don't know anything about flatseal, but I can wait if you plan to fix it sometime. Will just install a cronjob to delete this directory or so.

**Comment by felipehw** [comment]
@charlydelta , Zotero doesn't follow the XDG spec. If we make adjustments to enforce that ... previous installations would have problems (i tested this here - #74 - and gave up).

Your problems could be solved by running: `flatpak override --user --filesystem=home --filesystem=~/.zotero:rw --filesystem=~/Zotero:rw org.zotero.Zotero`.

You also can do this using a GUI tool ([Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)) and removing the configurations for `~/.zotero` `~/Zotero` and giveing access to `home`.

But the question about the better setup for this Flatpak remains ...

**Comment by lschmelzeisen** [comment]
Just if anyone runs into the same problem, I needed to modify the posted command to get this to work

```
flatpak override --user --filesystem /path/where/you/want/Zotero --nofilesystem ~/Zotero org.zotero.Zotero
```
