### ISSUE TITLE
No permissions zotero folder on external disk

### ISSUE THREAD

**Issue by dalanicolai** [flathub/org.zotero.Zotero#8]
I have my zotero folder installed on a separate NTFS partition, so that I can share it between windows and linux (I really need to work in Windows sometimes). However using this flathub package I can not acces the external disk. I found also [this](https://unix.stackexchange.com/questions/428059/cant-access-files-on-mounted-hd-from-inside-a-flatpack-application) on stackexchange. What do you think about changing the filesystem permissions (possibly in an alternative flathub package)?
It was an annoying surprise to see that the package did not work and it took precious time to find out why it did not work? Otherwise shouldn't this issue be mentioned in the package description?

**Comment by dalanicolai** [comment]
I tried to rebuild the package with --filesystem=host permissions. Although it seems to solve the issue I get a message "Gtk-Message: Failed to load module "pk-gtk-module". Does anybody know how to solve this? I already have the gtk-2.0 and gtk-3.0 modules "libpk-gtk-module.so" are installed (I am on fedora 28)

**Comment by amtlib-dot-dll** [comment]
Try `--filesystem=/run/media` rather than `--filesystem=host`?

**Comment by dalanicolai** [comment]
This indeeds seems a better choice. Although to make it a universally
useful package a list of mount points should be added (e.g. /media for
ubuntu).

**Comment by dalanicolai** [comment]
Until a decision is made, I guess it would be helpful to add information about the "flatpak override" option in the description...

**Comment by amtlib-dot-dll** [comment]
Thanks for your contribution.

**Comment by dalanicolai** [comment]
Thank for accepting it. I hope a better solution is decided upon soon
(although access to external disks is a general flathub issue)
