### ISSUE TITLE
Restore full access to home directory

### ISSUE THREAD

**Issue by dstillman** [flathub/org.zotero.Zotero#82]
Full home directory access was removed in #70 after the discussion in #65, which unfortunately has led to a spate of confused people in the Zotero Forums and on Twitter not understanding why they can't see all their folders. (Most recent is [here](https://forums.zotero.org/discussion/89108/zotero-does-not-list-complete-home-directory-when-browsing-files-for-attachment-in-ubuntu-20-04).)

Many Zotero users on Linux are unfamiliar with sandboxes (and/or don't even realize they're using a third-party package) and are confused by this behavior, which just seems like a bug in Zotero to them. As suggested by @danielwe in https://github.com/flathub/org.zotero.Zotero/issues/65#issuecomment-819921275, it's common for people to want to interact with other parts of the home directory, both when using native Zotero functions and particularly when using plugins.

We (the Zotero team) would like to ask that full home directory access be restored, which brings this package more in line with Zotero's intended behavior. People who want more restrictive access can manually disallow access.

**Comment by felipehw** [comment]
@dstillman 
Thanks for the feedback. I'll make the changes.

I would love it if the Zotero team takes the maintenance of the Flatpak :D.

But while we don't have an official Flatpak from Zotero, I'll help here. Just enter in contact if there are any other problems.

**Comment by hfiguiere** [comment]
a good start would be to build from source so it can be installed on an aarch64 machine (RaspberryPi, Chromebook). :-)
