### ISSUE TITLE
Clarify third-party nature of package

### ISSUE THREAD

**Issue by dstillman** [flathub/org.zotero.Zotero#83]
Thanks for maintaining this package.

It's not clear from the Flatpak description that this is a third-party package that's not produced by the Zotero team, and when people encounter [confusing issues with the package](https://github.com/flathub/org.zotero.Zotero/issues/82) they believe they're experiencing a Zotero bug.

We'd like to ask that a message similar to the one on [various](https://flathub.org/apps/details/com.slack.Slack) [other](https://flathub.org/apps/details/com.mojang.Minecraft) [packages](https://flathub.org/apps/details/com.discordapp.Discord) be added:

> NOTE: This wrapper is not verified by, affiliated with, or supported by the Zotero project.

If people come to the Zotero Forums with issues unrelated to the packaging, we'll do our best to help them, but they should know that they're using an unofficial version.

The "Developer" field should also be changed to "Corporation for Digital Scholarship", not "The Corporation for Digital Scholarship".

**Comment by dstillman** [comment]
Thank you!

**Comment by felipehw** [comment]
@dstillman 

The Zotero Team could be interested in maintaining the Flatpak package on Flathub?
The Flatpak package is a much easier way to install Zotero for Linux users and a lot of people are using it.

We'll keep maintaining the Flatpak package if Zotero Team aren't interested in it but I would prefer an official support :D.
