### ISSUE TITLE
Can not open attached pdfs from Zotero itself.

### ISSUE THREAD

**Issue by s-kesh** [flathub/org.zotero.Zotero#90]

**Comment by felipehw** [comment]
I have no problems here to open attached pdfs from Zotero (actually, it uses external PDF readers).
Without any kind of detailed information about what is happening and the system ,,, this issue will be closed.

**Comment by AntonOellerer** [comment]
Hey, I have the same problem and would be happy to assist in the debugging :)
I am using fedora 35 with flatpak 1.12.2 and zotero 5.0.96.3.
The default application is "Document Viewer" (evince).
The logging output by zotero is not really helpful I am afraid:
```
(3)(+0000487): Viewing attachment 1/LWKXV4JT

(3)(+0000002): Opening /home/antono/Zotero/storage/LWKXV4JT/Pham - 2015 - A Big Data Analytics Framework for IoT Application.pdf

(3)(+0000001): Notifier.trigger('open', 'file', [3]) called [observers: 2]

(3)(+0000000): Launching /home/antono/Zotero/storage/LWKXV4JT/Pham - 2015 - A Big Data Analytics Framework for IoT Application.pdf
```
I attached the full file below

[Debug Output.zip](https://github.com/flathub/org.zotero.Zotero/files/7808955/Debug.Output.zip)

**Comment by AntonOellerer** [comment]
Update:
I rebooted and now it works

**Comment by AntonOellerer** [comment]
Update:
After examining the problem further, it seems as if the file picker dialog appears behind the "Zotero" window if it is in fullscreen, thus being hidden, furthermore you cannot select it by alt-tabbing, so you have to make the window smaller to open the pdf.
