### ISSUE TITLE
Bump version to 6.x.x

### ISSUE THREAD

**Issue by 0b11001111** [flathub/org.zotero.Zotero#94]
Zotero 6 has just been released and I'd be happy to use the updated version :)

I've never contributed here but if you point me in the right direction I may be able to make a PR.

Thanks for your work!

**Comment by m8** [comment]
I'm also waiting for that :)

**Comment by felipehw** [comment]
@0b11001111 @m8 

Could you test this Flatpak to see if you find any problem?

https://github.com/flathub/org.zotero.Zotero/pull/97#issuecomment-1072499901

**Comment by m8** [comment]
hey @felipehw, no problem with the installation, works like a charm!

**Comment by steko** [comment]
It works really well. Thank you.
