### ISSUE TITLE
Can't extract annotations from pdf with zotfile

### ISSUE THREAD

**Issue by tenroc** [flathub/org.zotero.Zotero#98]
Hello,

Since the last Zotero flatpak update, I'm having issues with extracting annotations from pdfs with the Zotfile plugin (http://zotfile.com/) whereas it was working perfectly before. The option simply disappeared from the "attached files" contextual menu. 

Since the behaviour only appeared after a Zotero update, could it be related to the update? Could for instance a dependency not been met (zotfile uses pdf.js to extract annotations)?

**Comment by rvlobato** [comment]
Hi @tenroc “Extract Annotations” was a feature of the third-party ZotFile extension. In Zotero 6, that feature has been replaced by Zotero's own advanced PDF functionality. 

Please look at https://www.zotero.org/support/kb/zotfile_extract_annotations

**Comment by tenroc** [comment]
Oh wow. Thanks a lot! Sorry for cluttering the issue tracker. I'll close this.
